### ISSUE TITLE
For anyone compiling this, the version of VRCFaceTracking.Core must match.

### ISSUE THREAD

**Issue by aoirusann** [regzo2/PicoStreamingAssistantFTUDP#12]
En:
The release of VRCFaceTracking is 5.1.1.0, but if you clone the git repo, its assemly version is 5.1.1.1.
If you follow the instructions in [README_CN.md](https://github.com/regzo2/PicoStreamingAssistantFTUDP/blob/vrcfacetracking-module/README_CN.md) to compile, the included version of VRCFaceTracking.Core will be 5.1.1.1, which is not compatible with the release version 5.1.1.0.

The solution is to modify the `AssemblyVersion` to 5.1.1.0 when compiling: 
![image](https://github.com/regzo2/PicoStreamingAssistantFTUDP/assets/82883326/6027dfa6-d9b7-4c51-be12-3e19afbdc9ac)

中文：
从官网下的VRCFT是5.1.1.0版本的，但如果拉git库的话得到的是5.1.1.1版本，不兼容。
需要在编译时手动改一下版本号，如上图所示。

**Comment by aoirusann** [comment]
https://github.com/aoirusann/MyResourceServer/blob/main/Pico4SAFTExtTrackingModule.dll
Compiled by me, for VRCFT 5.1.1.0

**Comment by rogermiranda1000** [comment]
> if you clone the git repo, its assemly version is 5.1.1.1

@aoirusann looks like a https://github.com/benaclejames/VRCFaceTracking issue, not a problem from this repo (as you're complaining about the project you've cloned). Just for the record, mine is `<AssemblyVersion>5.0.2.0</AssemblyVersion>`.

**Comment by aoirusann** [comment]
> > if you clone the git repo, its assemly version is 5.1.1.1
> 
> @aoirusann looks like a https://github.com/benaclejames/VRCFaceTracking issue, not a problem from this repo (as you're complaining about the project you've cloned). Just for the record, mine is `<AssemblyVersion>5.0.2.0</AssemblyVersion>`.

Sorry for the rudeness. Just want to leave some mention.
Thank you for the work. :heart:
