### ISSUE TITLE
Release file format error

### ISSUE THREAD

**Issue by lonelyicer** [regzo2/PicoStreamingAssistantFTUDP#15]
Pico4ProModule.zip should contain the module.json file, not the metadata.json file.
![image](https://github.com/regzo2/PicoStreamingAssistantFTUDP/assets/63995099/a7d9dd9d-1113-469e-b8e5-7c0f61762bf5)
![image](https://github.com/regzo2/PicoStreamingAssistantFTUDP/assets/63995099/c99c1fd3-b49b-46ad-bb86-b1266eb2c3f6)

Rename metadata.json to module.json to make the zip recognised by vrcft.

**Comment by rogermiranda1000** [comment]
My bad, I'll make something to automatically build the zip. I'll leave this issue open until I do it.

**Comment by rogermiranda1000** [comment]
With https://github.com/regzo2/PicoStreamingAssistantFTUDP/pull/29 now the `bundle.sh` script should always provide the appropriate .zip
