### ISSUE TITLE
1.4 stuck on initializing

### ISSUE THREAD

**Issue by buddybopper** [regzo2/PicoStreamingAssistantFTUDP#20]
The newest module (1.4) causes vrcft to be stuck on initializing. I used the one from the module registry, not the github download, idk if that was the problem or not.

**Comment by rogermiranda1000** [comment]
Can you show the logs? Also, is PICO Connect and SteamVR launched?

**Comment by buddybopper** [comment]
Idk how to find the logs, pico streaming assistant is running and I am using vrc through steamvr

**Comment by rogermiranda1000** [comment]
VRCFT has a logs tab, check what does it say. It seems like it works for some users, so I don't think it's a problem with the .dll...

**Comment by TerayTech** [comment]
[latest.log](https://github.com/regzo2/PicoStreamingAssistantFTUDP/files/14935219/latest.log)
and here's my log, my operations are bellow:
open pico stream assistant -> open steamVR -> open VRCFT
it doesn't affect whether if VRC is on or off

**Comment by rogermiranda1000** [comment]
@buddybopper @TerayTech you say on 1.3 didn't happend, can you share the logs on that case?
Thanks, and sorry for the inconvenience.

**Comment by rogermiranda1000** [comment]
Also, can you try to launch VRCFT once SteamVR is on? Not before

**Comment by buddybopper** [comment]
[latest.log](https://github.com/regzo2/PicoStreamingAssistantFTUDP/files/14937976/latest.log)
here's the 1.3 log

**Comment by rogermiranda1000** [comment]
I noticed how you both use Streaming Assistant (and I didn't check that...) maybe that's the issue? I'll check it

**Comment by rogermiranda1000** [comment]
The issue seems to be on the retry loop, on the `Initialize` function: https://github.com/regzo2/PicoStreamingAssistantFTUDP/blob/27a199daf055e5a5728625831fb504e8919a3a69/PicoStreamingAssistantFTUDP/Pico4SAFTExtTrackingModule.cs#L69

I'll have to consider the consequences of removing that, and then push an update.

**Comment by rogermiranda1000** [comment]
Seems like the while is not needed, as at this part of the code the socket didn't have a timeout yet. If you close VRCFT it will close even if it's still connecting.

However, I noticed another bug: https://github.com/regzo2/PicoStreamingAssistantFTUDP/issues/22

**Comment by rogermiranda1000** [comment]
Solved on 1.4.1
